server:
  port: 8021
spring:
  #给项目来个名字
  application:
    name: rabbitmq-provider
  profiles:
    active: pro
  #配置rabbitMq 服务器
  rabbitmq:
    host: 172.17.222.9
    port: 5672
    username: admin
    password: 123456
    #虚拟host 可以不设置,使用server默认host
    virtual-host: my_vhost